apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: helm-guestbook
  repo: https://h.cfcr.io/codefreshdemo/demo
  version: 0.1.5
  releaseName: helm-guestbook-a-dev
  namespace: dev
  valuesFile: https://raw.githubusercontent.com/dustinvanbuskirk/helm-guestbook-environments/main/helm-guestbook-a/dev/values.yaml
